# Generated by Django 4.0.3 on 2022-04-12 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filiere', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etablissement',
            old_name='adress',
            new_name='adresse',
        ),
    ]
