# Generated by Django 4.0.3 on 2022-04-12 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filiere', '0002_rename_adress_etablissement_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='etablissement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filiere.etablissement'),
        ),
    ]
