# Generated by Django 3.2.12 on 2022-04-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiere', '0003_alter_filiere_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='niveau',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='website',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
